main: com.mercerenies.turtletroll.Main
name: A_Turtles_Troll
version: 1.9
api-version: 1.17
author: Mercerenies
description: Have fun :)
commands:
  turtle:
    description: Enable or disable features of A Turtle's Troll
    usage: /turtle <on|off|list> [feature]
    permission: com.mercerenies.turtletroll.turtle
