main: com.mercerenies.turtletroll.Main
name: A_Turtles_Troll
version: 1.10
api-version: 1.17
author: Mercerenies
description: Have fun :)
commands:
  turtle:
    description: Enable or disable features of A Turtle's Troll
    usage: /turtle <on|off|list|bedtime> [feature]
permissions:
  com.mercerenies.turtletroll.command:
    default: true
  com.mercerenies.turtletroll.command.bedtime:
    default: true
  com.mercerenies.turtletroll.feature.list:
    default: true
  com.mercerenies.turtletroll.feature.toggle:
    default: op
